### ISSUE TITLE
Quest kyle's gone missing

### ISSUE THREAD

**Issue by rec0d** [MillipedeAS/onyx-wow#17]
When showing him item meat, he ignore it and keeps running [location] bloodhoof village

**Comment by MillipedeAS** [comment]
Invalid has just tested and completed the quest fine.

Tender strider meat: 33009
Kyle: 23616
Quest: 11129

Noticed there was two spawns of kyle though, the frenzied and friendly. If you tested meat on friendly kyle. Then he would not accept the meat.

**Comment by MillipedeAS** [comment]
* server is online.

**Comment by rec0d** [comment]
when try to fed  frenzied kyle the dosnt notice the food and keep running away.

**Comment by MillipedeAS** [comment]
Try to enable your mmaps.
