### ISSUE TITLE
creature: spawn missing quest: rites of the earthmother [Location] North of Mulgore

### ISSUE THREAD

**Issue by rec0d** [MillipedeAS/onyx-wow#19]
spawn entry 3058 for arra'chea and missing the pack for kodo´s

**Comment by MillipedeAS** [comment]
He's not supposed to be followed by a pack of kodo's?

**Comment by rec0d** [comment]
yes, youre right so just need to spawn her at her location

**Comment by MillipedeAS** [comment]
She's already there, do you use the latest world database?
