### ISSUE TITLE
Npc: rumstag proudstider lend in quest bug [Location] Thunderbluff

### ISSUE THREAD

**Issue by rec0d** [MillipedeAS/onyx-wow#20]
entry: 14728 rumstag proudstider after donate 60 wool cloth he stil has a questmarker but cant give him more cloth. the quest mark should disapear. When relog the quest mark has disapear as it should.

**Comment by MillipedeAS** [comment]
Are you using the same core as me? 

Because 50% of your reports isn't bugged on this core.
He works as intended, issue closed.
