### ISSUE TITLE
Druid quest: lession to learn: makes client crash [Location] moonglade

### ISSUE THREAD

**Issue by rec0d** [MillipedeAS/onyx-wow#22]
http://www.wowhead.com/quest=26/a-lesson-to-learn

when you lend in the quest in moonglade. you get a countdown time for your next quest. and the game freezes. and client crashes, try to relogin again and the game is still freezing.

**Comment by MillipedeAS** [comment]
Try to delete cache, I can do the quest just fine.

**Comment by rec0d** [comment]
Where did you get your client?
Den 19 aug 2016 10:09 skrev "MillipedeAS" <notifications@github.com>:
