### ISSUE TITLE
Rogue Stealth cant mount

### ISSUE THREAD

**Issue by rec0d** [MillipedeAS/onyx-wow#6]
when in stealth mode trying to mount up you get the message youre in shapeshift form

**Comment by MillipedeAS** [comment]
Compiling your fix right now, i'll lose this if it works! :-)

**Comment by MillipedeAS** [comment]
Fixed.

Commit: https://github.com/MillipedeAS/onyx-wow/commit/2061c71ae6222d2f3c0c5485fd868179ee6777b1
